"use client";

import { useState } from "react";
import { ArrowLeft, Atom, BookOpen, Brain, CaretRight, CheckCircle, Circuitry, Function, Key, Lightning, LockKey, Medal, Play, ShieldCheck, Sparkle, Target, Warning, XCircle } from "@phosphor-icons/react";

const videos = {
  qkd: ["R0SOqLwLOR0", "Outsmarting Hackers: Quantum Key Distribution Explained", "Qiskit"],
  basics: ["3-c4xJa7Flk", "Single Systems | Understanding Quantum Information & Computation", "Qiskit"],
  entanglement: ["GSsElSQgMbU", "Entanglement in Action", "Qiskit"],
  grover: ["hnpjC8WQVrQ", "Grover’s Algorithm", "Qiskit"],
  pqc: ["9NKm84vKALc", "Short course on Kyber (ML-KEM) and Dilithium (ML-DSA)", "Alfred Menezes"],
};

const sections = [
  { level:"Foundation", title:"Classical Cryptography and the Key-Distribution Problem", time:"25 min", icon:Key, video:"qkd",
    objectives:["Distinguish confidentiality, integrity, authentication, and key establishment.","Explain symmetric encryption, public-key cryptography, signatures, and one-time pads.","Identify the key-distribution problem QKD addresses."],
    content:[["Cryptography is more than encryption","Confidentiality hides content, integrity detects modification, authentication identifies communicators, and key establishment creates or transports key material. These are separate jobs."],["Symmetric and public-key cryptography","AES efficiently protects bulk data once both parties share a secret. Public-key systems help distribute keys and establish identity; RSA relies on factoring and elliptic-curve systems on discrete logarithms."],["The one-time pad and key problem","A one-time pad offers information-theoretic secrecy when its random, message-length key stays secret and is never reused. Securely distributing that much key material is difficult."],["Alice, Bob, and Eve","QKD creates shared secret key material for later symmetric encryption. Alice sends, Bob receives, and Eve represents an eavesdropper; QKD is not itself a bulk-data encryption algorithm."]],
    keyIdea:"QKD normally establishes key material; it does not send application data through quantum encryption.",
    lab:"Classify security controls as confidentiality, integrity, authentication, or key establishment. Then trace how Alice and Bob obtain the symmetric key used for bulk encryption.",
    quiz:[["Which goal prevents unauthorized reading?",["Integrity","Confidentiality","Authentication"],1,"Confidentiality hides message contents."],["Why is a one-time pad difficult at scale?",["It uses public keys","It needs a secret message-length random key that is never reused","It cannot encrypt bits"],1,"Distributing and managing the large one-use key is difficult."],["What is QKD’s primary output?",["Encrypted application data","A signature","Shared secret key material"],2,"QKD establishes key material for later use."],["What problem connects classical cryptography to QKD?",["Secure key distribution","Screen brightness","File compression"],0,"QKD addresses secure establishment of shared key material."],["Which is a public-key cryptography job?",["Bulk video encryption only","Digital signatures or key establishment","Photon detection"],1,"Public-key systems support signatures, authentication, and key establishment or transport."]], algorithms:["RSA","Diffie–Hellman"] },
  { level:"Foundation", title:"Quantum Information Foundations for Cryptography", time:"30 min", icon:Atom, video:"basics",
    objectives:["Represent |0⟩, |1⟩, |+⟩, and |−⟩.","Explain Z- and X-basis measurement.","Use superposition, gates, and entanglement in a cryptographic context."],
    content:[["Bits and qubits","A qubit is a normalized superposition α|0⟩+β|1⟩ whose amplitudes determine measurement probabilities. One measurement still returns one classical outcome."],["Z and X bases","Z is {|0⟩,|1⟩}; X is |+⟩=(|0⟩+|1⟩)/√2 and |−⟩=(|0⟩−|1⟩)/√2. Matching bases recover the encoded bit ideally; incompatible bases give random outcomes."],["Measurement and gates","Measurement extracts classical information and generally changes the state. X swaps |0⟩ and |1⟩; H converts between Z and X descriptions."],["Entanglement","An entangled state cannot be separated into independent subsystem states. The Bell state (|00⟩+|11⟩)/√2 supports entanglement-based QKD ideas."]],
    keyIdea:"Choosing the wrong measurement basis can destroy information that the receiver wanted to preserve.",
    lab:"Prepare |0⟩, |1⟩, |+⟩, and |−⟩. Measure each repeatedly in Z and X, comparing deterministic matching-basis results with approximately 50/50 incompatible-basis results.",
    quiz:[["What can one Z-basis measurement return?",["Both 0 and 1","A classical 0 or 1","The amplitudes"],1,"A measurement returns one classical outcome."],["Measure |0⟩ in X. The ideal result is…",["Always 0","Always 1","Random with equal probabilities"],2,"|0⟩ has equal overlap with |+⟩ and |−⟩."],["Which gate changes between Z and X descriptions?",["Hadamard H","CNOT only","Toffoli"],0,"H maps the Z and X basis states."],["Which pair forms the X basis?",["|0⟩ and |1⟩","|+⟩ and |−⟩","|00⟩ and |11⟩"],1,"The X basis contains |+⟩ and |−⟩."],["What distinguishes an entangled pair?",["It is always two classical bits","Its joint state cannot be separated into independent subsystem states","It cannot be measured"],1,"Entanglement creates a joint state that does not factor into independent states."]] },
  { level:"Foundation", title:"Why Quantum Information Can Reveal Eavesdropping", time:"25 min", icon:Warning, video:"qkd",
    objectives:["Explain measurement disturbance and basis uncertainty.","State no-cloning accurately.","Connect both ideas to intercept-resend."],
    content:[["Unknown states cannot simply be read and restored","Eve does not know the preparation basis. A wrong-basis measurement gives no reliable original bit and can make the resent state inconsistent with Alice’s preparation."],["No-cloning theorem","No universal operation perfectly copies an arbitrary unknown quantum state. Eve cannot save perfect backups and wait for basis disclosure."],["Intercept-resend","If Eve measures every signal in a random Z/X basis and resends it, wrong-basis choices produce about 25% QBER among attacked sifted bits in the ideal model."],["Statistics and authentication","Noise also creates errors, so detection is statistical. The classical channel still needs authentication to prevent a man-in-the-middle."]],
    keyIdea:"QKD bounds information leakage statistically under a stated security model; it does not reveal every intrusion immediately.",
    lab:"Simulate intercept-resend at 0%, 25%, 50%, and 100% attack rates. Plot attack fraction against observed QBER and explain why one mismatch is not proof of Eve.",
    quiz:[["Why can Eve not save perfect copies?",["No-cloning forbids universal perfect copying","Photons have no state","The classical channel deletes them"],0,"No-cloning applies to arbitrary unknown states."],["Full ideal intercept-resend yields about what QBER?",["0%","25%","100%"],1,"Half Eve’s bases are wrong and half those results disagree."],["Why authenticate the classical channel?",["Prevent impersonation","Reduce optical loss","Create entanglement"],0,"Quantum disturbance does not identify the classical speaker."],["What creates intercept-resend errors?",["Eve sometimes measures in the wrong basis","Bob publishes the final key","The fiber factors RSA"],0,"A wrong-basis measurement disturbs the original encoding."],["Does one mismatch prove Eve is present?",["Always","No, ordinary noise can also create errors","Only in the X basis"],1,"Detection uses statistics because real channels are noisy."]] },
  { level:"Core QKD", title:"Quantum Key Distribution: Architecture and Security Model", time:"30 min", icon:Circuitry, video:"qkd",
    objectives:["Describe quantum and classical channels.","Differentiate raw, sifted, and final keys.","Place authentication and key management around QKD."],
    content:[["What QKD produces","Alice and Bob derive matching secret bits while bounding Eve’s possible information. The output is key material, not the application message."],["Two channels","Quantum states use a quantum channel. Basis announcements, parameter estimation, reconciliation, privacy amplification, and key management use a public but authenticated classical channel."],["Key lifecycle","Raw detections → sifting → parameter estimation/QBER → reconciliation → privacy amplification → final secret key → key-consuming application."],["System security","QKD does not replace endpoint protection, secure key stores, identity, APIs, monitoring, or patching. Deployable QKD is an ICT systems problem."]],
    keyIdea:"Protocol security is one layer inside an authenticated, monitored, correctly implemented system.",
    lab:"Draw the complete QKD architecture from quantum source to key-consuming application. Mark the trust boundary, authentication, key store, monitoring, and public messages.",
    quiz:[["Which channel carries quantum states?",["Quantum channel","Database","Key store"],0,"Prepared quantum signals use the quantum channel."],["Must the classical QKD channel be secret?",["Always","No, but it must be authenticated","It cannot exist"],1,"Public discussion is allowed; identity authentication is essential."],["Choose the correct order.",["Sifting → raw detection","Raw detection → sifting → reconciliation → privacy amplification","Privacy amplification → measurement"],1,"Post-processing follows raw detection and sifting."],["What is the main output of QKD?",["A shared secret key","A public certificate","An application message"],0,"The protocol produces shared secret key material."],["Which control does QKD still require?",["Endpoint protection and secure key storage","No identity checks","Public private keys"],0,"QKD does not remove conventional endpoint, identity, and key-management security."]] },
  { level:"Core QKD", title:"BB84 Protocol: Full Walkthrough", time:"35 min", icon:Function, video:"qkd",
    objectives:["Execute BB84 by hand.","Map bits and bases to four states.","Explain sifting and sample comparison."],
    content:[["1. Alice prepares","Alice chooses random bits and bases. Z maps 0→|0⟩, 1→|1⟩; X maps 0→|+⟩, 1→|−⟩. She sends those states."],["2. Bob measures","Bob independently chooses Z or X. Matching bases recover Alice’s bit ideally; different bases give random results."],["3. Announce and sift","They reveal only basis choices and keep matching positions. Uniform independent basis choices match about half the time."],["4. Estimate and post-process","They reveal and discard a random sifted sample to estimate QBER, reconcile disagreements, and apply privacy amplification."],["Circuit intuition","X and H encode BB84 states in a simulator; H before computational measurement implements X-basis readout. This models protocol logic, not deployed optical transmission."]],
    keyIdea:"Keep a position only when Alice’s preparation basis matches Bob’s measurement basis.",
    lab:"Run BB84 without Eve: generate Alice’s bits and bases and Bob’s bases, simulate measurements, sift the results, and calculate the sifted-key ratio and ideal QBER.",
    quiz:[["Which state represents X-basis bit 1?",["|+⟩","|−⟩","|0⟩"],1,"X maps bit 1 to |−⟩."],["About what fraction survives uniform sifting?",["25%","50%","100%"],1,"Independent binary basis choices match half the time."],["Why discard revealed QBER sample bits?",["They are public","They are always wrong","They use Z"],0,"Revealed bits are no longer secret."],["What may Alice and Bob announce after transmission?",["Their basis choices","The final secret key","Their random seeds"],0,"Basis choices can be compared without revealing unrevealed bit values."],["What do they reveal to estimate QBER?",["A random subset of sifted bit values","All remaining secret bits","Only detector names"],0,"A sampled subset estimates errors and is then discarded."]] },
  { level:"Core QKD", title:"QKD Post-Processing: From Raw Measurements to a Secret Key", time:"30 min", icon:LockKey, video:"basics",
    objectives:["Calculate QBER.","Explain reconciliation and privacy amplification.","Understand finite-key analysis, authentication, and aborts."],
    content:[["QBER and estimation","QBER = mismatches/compared bits. Noise, devices, or attacks cause errors. A sample estimates the unseen block with finite-size uncertainty."],["Information reconciliation","Public error-correction messages align Alice’s and Bob’s strings but leak correlated parity information to Eve."],["Privacy amplification","Public compression transforms the reconciled string into a shorter key about which Eve’s information is negligible under the proof."],["Authentication and abort","A short authentication key can bootstrap key growth. High errors, alarms, failed authentication, or weak statistics must cause a secure abort."]],
    keyIdea:"12 mismatches in 400 bits gives 3% QBER; the security decision also depends on protocol and proof assumptions.",
    lab:"Start with two similar bit strings. Perform toy parity-based reconciliation, record each disclosed parity value, then hash the reconciled string to model privacy amplification.",
    quiz:[["10 mismatches among 250 bits gives…",["2%","4%","10%"],1,"10/250 = 4%."],["Why does reconciliation reduce secrecy?",["Public messages leak correlated information","It deletes every bit","It removes authentication"],0,"Leakage reduces safe final key length."],["What happens when the bound is unacceptable?",["Always output a key","Securely abort","Publish the raw key"],1,"Secure abort is essential."],["What is privacy amplification for?",["Compressing a partially secret string to reduce Eve’s information","Increasing optical power","Publishing parity bits"],0,"Privacy amplification shortens the key to remove potential leakage."],["Why is the final key shorter than the sifted key?",["Testing, reconciliation leakage, and privacy amplification consume length","The Z basis cannot store bits","AES requires it"],0,"Security processing reveals or removes information before final key use."]] },
  { level:"Intermediate QKD", title:"Beyond BB84: B92, Entanglement-Based QKD, and Decoy States", time:"30 min", icon:Sparkle, video:"entanglement",
    objectives:["Recognize major QKD families.","Explain entanglement-based QKD.","Explain why weak lasers motivate decoy states."],
    content:[["B92","B92 uses two non-orthogonal states, showing that security is rooted in imperfect distinguishability rather than one fixed four-state recipe."],["Entanglement-based QKD","E91 and BBM92 distribute entangled pairs. Measurement correlations support security reasoning and connect to repeaters and device-independent concepts."],["Practical light sources","Attenuated laser pulses have probabilistic photon counts; multi-photon pulses create attacks absent from the ideal single-photon model."],["Decoy states","Alice varies pulse intensity secretly, then discloses it. Intensity-dependent statistics help estimate single/multi-photon behavior and detect photon-number-splitting exploitation."]],
    keyIdea:"Protocol choice depends on assumptions, key rate, distance, device behavior, and network architecture.",
    lab:"Build a comparison table for BB84, B92, E91/BBM92, and decoy-state BB84. Record the states or resources, device assumptions, practical motivation, and main trade-offs.",
    quiz:[["How many states does basic B92 use?",["Two","Four","Eight"],0,"B92 is a two-state protocol."],["What resource is central to E91?",["Factoring","Entanglement","RSA"],1,"E91 uses entangled pairs."],["What do decoy states vary?",["Pulse intensity","Fiber length","Final AES key"],0,"Different mean photon numbers expose channel/source behavior."],["Why do weak laser pulses complicate ideal BB84?",["Their photon count is probabilistic","They always contain zero photons","They reveal the AES key"],0,"Some weak coherent pulses contain multiple photons, creating additional attack opportunities."],["Why must protocol security include implementation assumptions?",["Physical sources and detectors may differ from the ideal model","Every protocol uses RSA","The classical channel is always secret"],0,"Real component behavior can invalidate assumptions used by a proof."]] },
  { level:"Intermediate QKD", title:"Practical QKD: Hardware, Distance, Noise, and Implementation Attacks", time:"35 min", icon:Warning, video:"qkd",
    objectives:["Identify optical components.","Explain loss and detector limits.","Recognize implementation attacks and countermeasures."],
    content:[["Typical components","Sources, modulators, entropy, attenuators, fiber/free-space optics, single-photon detectors, synchronization, post-processing, and key management form the system."],["Loss and imperfections","Detection falls with distance while background matters more. Timing, detector mismatch, reflections, unwanted modes, and imperfect modulators can violate proof assumptions."],["Implementation attacks","Trojan-horse probes analyze reflections; detector-control attacks exploit response. They attack model-to-device gaps, not quantum mechanics."],["Countermeasures and networks","Isolation, filters, monitoring, randomization, characterization, stronger models, and MDI designs help. Trusted relays extend distance but add trust."]],
    keyIdea:"A mathematically secure protocol can fail when the physical device violates its proof model.",
    lab:"Analyze a hypothetical transmitter and receiver for timing leaks, detector mismatch, back-reflections, and unwanted modes. Propose monitoring, isolation, characterization, and operational controls.",
    quiz:[["Why does distance reduce useful detections?",["Optical loss","No-cloning","Privacy amplification"],0,"More photons are lost."],["A Trojan-horse attack…",["Factors RSA","Injects light and studies reflections","Changes QBER math"],1,"Reflections may expose internal settings."],["Trusted relays add what assumption?",["Relays protect key material","All photons are copied","Classical channels are secret"],0,"Relay infrastructure must be trusted."],["Do detector-control attacks disprove quantum mechanics?",["Yes","No, they exploit implementation/model gaps","Only at long distance"],1,"They target physical behavior outside the idealized protocol model."],["Which is a useful countermeasure category?",["Optical isolation and monitoring","Removing authentication","Reusing final keys"],0,"Isolation, filters, watchdogs, randomization, and device characterization can reduce implementation risk."]] },
  { level:"Intermediate QKD", title:"Quantum Randomness and Random Number Generation", time:"25 min", icon:Target, video:"basics",
    objectives:["Explain why keys need randomness.","Distinguish CSPRNGs and physical entropy.","Connect quantum measurement to randomness."],
    content:[["Why randomness matters","Keys, nonces, salts, challenges, basis choices, and samples must be unpredictable; weak randomness defeats strong mathematics."],["Pseudorandom and physical","A CSPRNG expands hidden state deterministically. A physical RNG collects entropy; practical systems combine collection, conditioning, health tests, and deterministic generation."],["Quantum RNG","Measuring |+⟩ in Z gives balanced raw bits ideally. Production QRNGs must model devices, quantify entropy, monitor failure, and extract randomness."],["Testing is not proof","Statistical tests reveal some bias but cannot prove adversarial unpredictability. The source and implementation model still matter."]],
    keyIdea:"Mini-lab: measure |+⟩ 10,000 times, add bias, and compare “looks random” with quantified entropy.",
    lab:"Measure |+⟩ in Z for 10,000 shots and plot the counts. Add a controlled software bias, measure it, and explain why a frequency test alone cannot prove adversarial unpredictability.",
    quiz:[["A CSPRNG…",["Expands secret state deterministically","Measures photons only","Publishes seeds"],0,"Its hidden state determines output designed to be unpredictable."],["Simple QRNG demonstration?",["Measure |+⟩ repeatedly in Z","Clone |+⟩","Use it as an RSA prime"],0,"Ideal outcomes are balanced."],["Does 50/50 prove security?",["Yes","No; source and adversary models matter","Only in BB84"],1,"Predictable sources can pass simple tests."],["Which values need strong randomness?",["Keys, nonces, salts, and basis choices","Only filenames","Public documentation"],0,"Predictability in cryptographic choices can defeat strong algorithms."],["Where does BB84 use randomness?",["Alice’s bits and bases, Bob’s bases, and sampling","Only in the final UI","It does not use randomness"],0,"Random choices are part of BB84’s security model."]] },
  { level:"Quantum-safe", title:"Quantum Attacks on Classical Cryptography: Shor and Grover", time:"35 min", icon:Lightning, video:"grover",
    objectives:["Explain Shor’s threatened problems.","Explain Grover’s quadratic advantage.","Reject the claim that quantum breaks everything."],
    content:[["Shor’s algorithm","Quantum factoring and discrete-log methods threaten RSA, DH/DSA, ECDH, and elliptic-curve signatures by reversing their assumed-hard foundations."],["Current hardware","Modern-key attacks require large fault-tolerant machines far beyond small educational demonstrations."],["Grover and hashes","Grover reduces unstructured search from about N to √N queries. Larger symmetric and hash parameters can restore margin."],["Harvest now, decrypt later","Adversaries may record vulnerable traffic now and decrypt it later, making long-lived confidentiality a present migration concern."]],
    keyIdea:"Shor structurally threatens RSA/DH/ECC; Grover gives a quadratic generic-search speedup.",
    lab:"Run small educational Shor and Grover demonstrations, such as factoring 15 and searching a tiny space. Separate the demonstration scale from the resources required for cryptographic attacks.",
    quiz:[["Shor targets which RSA problem?",["Factoring","Sorting","Randomness"],0,"RSA depends on factoring hardness."],["Grover’s speedup is…",["Exponential","Quadratic","None"],1,"Queries drop roughly N→√N."],["Can current machines factor RSA-2048 practically?",["Yes","No","Only with AES"],1,"Required fault-tolerant resources do not exist today."],["Which families are threatened by quantum discrete-log methods?",["DH, ECDH, and elliptic-curve signatures","AES only","Compression algorithms"],0,"Shor-related discrete-log algorithms threaten finite-field and elliptic-curve public-key systems."],["What is harvest now, decrypt later?",["Recording vulnerable ciphertext now for future decryption","Deleting keys immediately","Running Grover on public videos"],0,"Long-lived encrypted data can be collected before a cryptographically relevant quantum computer exists."]], algorithms:["RSA","ECDH","ECDSA"] },
  { level:"Quantum-safe", title:"Post-Quantum Cryptography and NIST Standards", time:"35 min", icon:ShieldCheck, video:"pqc",
    objectives:["Distinguish PQC from QKD.","Explain ML-KEM, ML-DSA, and SLH-DSA.","Understand migration and crypto-agility."],
    content:[["PQC is classical","PQC runs on ordinary computers using problems believed hard for quantum attackers. QKD uses quantum states and specialized communication hardware."],["NIST standards","FIPS 203 specifies ML-KEM for shared secrets; FIPS 204 specifies ML-DSA signatures; FIPS 205 specifies hash-based SLH-DSA signatures."],["KEM versus signature","A KEM establishes secret material. A signature provides authenticity and integrity; it does not provide confidentiality."],["Migration and agility","RSA/ECC appear in TLS, SSH, VPNs, tokens, signing, PKI, HSMs, and stored formats. Crypto-agility includes inventory, policy, negotiation, testing, observability, rollback, and retirement."],["QKD and PQC","PQC scales across software infrastructure; QKD can serve selected controlled high-value links. Their roles can be complementary."]],
    keyIdea:"ML-KEM = key establishment. ML-DSA/SLH-DSA = signatures. All are classical post-quantum algorithms.",
    lab:"Benchmark available ML-KEM and ML-DSA implementations. Record key generation, encapsulation or signing latency, CPU and memory use, and key, ciphertext, and signature sizes.",
    quiz:[["ML-KEM performs…",["Key encapsulation","Signatures","Teleportation"],0,"ML-KEM establishes shared secrets."],["ML-DSA and SLH-DSA perform…",["Bulk encryption","Digital signatures","Photon detection"],1,"Both are signature standards."],["Correct mapping?",["203 ML-KEM; 204 ML-DSA; 205 SLH-DSA","203 RSA; 204 AES","All are QKD"],0,"These are NIST’s initial PQC standards."],["Does PQC require a quantum computer?",["Yes","No, it runs on classical computers","Only for signatures"],1,"PQC uses classical algorithms designed to resist quantum attackers."],["What does crypto-agility include?",["Inventory, negotiation, testing, replacement, observability, and retirement","One permanent algorithm","Hiding algorithm names"],0,"Migration requires lifecycle controls, compatible protocols, and operational visibility."]], algorithms:["RSA","ECDH","EdDSA / Ed25519"] },
  { level:"Quantum-safe", title:"Hybrid Quantum-Safe Systems and Capstone Design", time:"40 min", icon:Brain, video:"pqc",
    objectives:["Combine QKD, PQC, symmetric cryptography, and authentication.","Explain hybrid key establishment.","Design and evaluate a quantum-safe architecture."],
    content:[["Why hybrid approaches exist","Soundly combining independent mechanisms can preserve security when at least one remains secure under the model."],["PQC plus classical","A classical key-establishment secret and PQC KEM secret can be combined. The protocol and combiner require standardization or careful review."],["QKD plus authentication","QKD needs an authenticated classical channel via pre-shared keys or signatures. Final QKD keys feed encryption, MACs, and key management."],["Where QKD fits","QKD suits controlled high-value links with optical infrastructure and specialized operations more than universal consumer Internet deployment."],["Capstone and metrics","Design a link with authenticated classical and QKD paths, QBER monitoring, post-processing, key management, ML-KEM, ML-DSA, rotation, audit, and fallback. Measure key rate, leakage, latency, sizes, aborts, and operational cost."]],
    keyIdea:"Start with the asset, confidentiality lifetime, network, adversary, hardware, trust, cost, and operational constraints.",
    lab:"Design a service that obtains key material from simulated BB84, ML-KEM, or a hybrid mode. Derive application keys with a KDF, rotate them, record provenance, and expose metrics and audit logs.",
    quiz:[["Why use hybrid key establishment?",["Remove authentication","Retain security if one soundly combined component remains secure","Make keys public"],1,"A reviewed hybrid reduces reliance on one component."],["Why authenticate QKD?",["Stop impersonation","Increase photon speed","Run Grover"],0,"An attacker could impersonate both parties."],["What must architecture comparisons document?",["Only colors","Security assumptions and threat model","Only key rate"],1,"Metrics require explicit assumptions and threats."],["Where is QKD most plausible?",["Controlled high-value optical links","Every consumer webpage by default","Offline calculators only"],0,"QKD fits controlled links where the information value and confidentiality lifetime justify specialized infrastructure."],["Which evaluation set is useful?",["QBER, final key rate, latency, leakage, sizes, aborts, and operational cost","Only logo color","Only raw photon count"],0,"A useful evaluation combines security, performance, failure, and operational metrics."]], algorithms:["Diffie–Hellman","ECDH","RSA"] },
];

export default function QuantumCourse({answers,setAnswers,onOpenAlgorithm}){
  const [courseQuery,setCourseQuery]=useState("");
  const [activeItem,setActiveItem]=useState(null);
  const answer=(sectionIndex,questionIndex,choiceIndex)=>setAnswers(previous=>({...previous,[sectionIndex]:{...(previous[sectionIndex]||{}),[questionIndex]:choiceIndex}}));
  const openItem=(sectionIndex,type)=>{setActiveItem({sectionIndex,type});window.scrollTo({top:0,behavior:"smooth"})};

  if(!activeItem){
    return <div className="course-shell course-library">
      <section className="library-hero"><span className="eyebrow">CYBERQ LAB LEARNING</span><h1>Find all courses</h1><p>Build practical skills in quantum computing, cybersecurity, and quantum-safe system design.</p></section>
      <div className="library-toolbar"><div><b>Available courses</b><span>1 course</span></div><label><span>Search courses</span><input type="search" value={courseQuery} onChange={event=>setCourseQuery(event.target.value)} placeholder="Search by topic" aria-label="Search courses"/></label></div>
      <div className="course-library-grid">{"quantum cryptography qkd bb84 post-quantum cybersecurity".includes(courseQuery.trim().toLowerCase())?<article className="course-card"><div className="course-card-cover"><span><Atom size={34} weight="duotone"/></span><small>FOUNDATIONS</small><strong>Quantum<br/>Cryptography</strong><i>CyberQ Lab</i></div><div className="course-card-copy"><div className="course-card-tags"><span>Quantum security</span><span>Beginner → intermediate</span></div><h2>Quantum Cryptography</h2><p>Learn QKD, BB84, implementation security, quantum threats, post-quantum cryptography, and hybrid system design.</p><div className="course-card-meta"><span><BookOpen size={16}/>12 sections</span><span><Target size={16}/>60 quiz questions</span></div><button onClick={()=>openItem(0,"lesson")}>View course <CaretRight size={17}/></button></div></article>:<div className="course-library-empty"><BookOpen size={28}/><b>No courses found</b><span>Try a different topic or keyword.</span></div>}</div>
    </div>;
  }

  if(activeItem){
    const {sectionIndex,type}=activeItem, section=sections[sectionIndex], Icon=section.icon, a=answers[sectionIndex]||{}, video=videos[section.video];
    const done=Object.keys(a).length===section.quiz.length, score=section.quiz.reduce((n,q,i)=>n+(a[i]===q[2]?1:0),0);
    const labels={lesson:"Lesson and video",practice:"Algorithm practice",quiz:"Section quiz"};
    return <div className="course-reader-shell">
      <aside className="course-reader-nav">
        <button className="reader-back" onClick={()=>setActiveItem(null)}><ArrowLeft size={19}/> <span>All courses</span></button>
        <div className="reader-course-name"><small>CYBERQ LAB COURSE</small><h2>Quantum Cryptography</h2><p>Basic to intermediate</p></div>
        <div className="reader-nav-divider"/><b className="reader-nav-label">Lessons</b>
        <nav>{sections.map((navSection,navIndex)=>{const current=navIndex===sectionIndex;return <div className={`reader-nav-section ${current?"current":""}`} key={navSection.title}><button onClick={()=>openItem(navIndex,"lesson")}><span>{String(navIndex+1).padStart(2,"0")}</span>{navSection.title}<CaretRight size={14}/></button>{current&&<div className="reader-subnav"><button className={type==="lesson"?"active":""} onClick={()=>openItem(navIndex,"lesson")}>Lesson and video</button>{navSection.algorithms&&<button className={type==="practice"?"active":""} onClick={()=>openItem(navIndex,"practice")}>Algorithm practice</button>}<button className={type==="quiz"?"active":""} onClick={()=>openItem(navIndex,"quiz")}>Section quiz</button></div>}</div>})}</nav>
      </aside>
      <main className="course-resource-page">
      <div className="resource-topbar"><span>{section.level}</span><span>Section {sectionIndex+1} of 12</span></div>
      <section className="reader-hero"><span className="lesson-icon"><Icon size={27} weight="duotone"/></span><div><small>{section.level} · {labels[type]}</small><h1>{section.title}</h1><p>{section.objectives[0]}</p></div></section>
      {type==="lesson"&&<main className="resource-content"><section className="reader-objectives"><Target size={19}/><div><b>Learning objectives</b><ul>{section.objectives.map(x=><li key={x}>{x}</li>)}</ul></div></section><div className="reader-content">{section.content.map(([title,copy],contentIndex)=><article key={title}><span>{String(contentIndex+1).padStart(2,"0")}</span><div><h2>{title}</h2><p>{copy}</p></div></article>)}</div><section className="reader-key-idea"><Sparkle size={21} weight="fill"/><div><b>Key idea</b><p>{section.keyIdea}</p></div></section><section className="lesson-activity"><Circuitry size={24} weight="duotone"/><div><small>PRACTICAL ACTIVITY</small><h2>Apply what you learned</h2><p>{section.lab}</p></div></section><section className="course-video resource-video"><div className="video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${video[0]}?rel=0`} title={video[1]} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/></div><div><span><Play size={16} weight="fill"/> RECOMMENDED VIDEO</span><h3>{video[1]}</h3><p>{video[2]} · YouTube privacy-enhanced embed.</p><a href={`https://www.youtube.com/watch?v=${video[0]}`} target="_blank" rel="noreferrer">Open on YouTube ↗</a></div></section></main>}
      {type==="practice"&&<section className="resource-practice"><Function size={28} weight="duotone"/><div><small>INTERACTIVE PRACTICE</small><h2>{section.algorithms?"Choose an algorithm whiteboard":"Review this section in the cryptography lab"}</h2><p>Use an animated playground to connect the lesson with each calculation and security step.</p>{section.algorithms&&<div>{section.algorithms.map(name=><button onClick={()=>onOpenAlgorithm(name)} key={name}>{name}<CaretRight size={15}/></button>)}</div>}</div></section>}
      {type==="quiz"&&<section className="section-mcq resource-quiz"><div className="mcq-heading"><div><Target size={20}/><span><small>REQUIRED SECTION QUIZ</small><h2>Check your understanding</h2></span></div><strong>{done?`${score}/${section.quiz.length} marks`:`${Object.keys(a).length}/${section.quiz.length} answered`}</strong></div><p>Answer every question to complete this section. Answers can be revised.</p><div className="mcq-list">{section.quiz.map(([question,choices,right,explanation],questionIndex)=>{const chosen=a[questionIndex],attempted=chosen!==undefined,correct=chosen===right;return <article className={attempted?(correct?"correct":"incorrect"):""} key={question}><div className="mcq-question"><span>{questionIndex+1}</span><h3>{question}</h3>{attempted&&<em>{correct?"+1":"0"}</em>}</div><div className="mcq-options">{choices.map((choice,choiceIndex)=><button onClick={()=>answer(sectionIndex,questionIndex,choiceIndex)} className={`${chosen===choiceIndex?"selected":""} ${attempted&&choiceIndex===right?"answer":""}`} key={choice}><span>{String.fromCharCode(65+choiceIndex)}</span>{choice}{attempted&&choiceIndex===right&&<CheckCircle size={17} weight="fill"/>}{attempted&&chosen===choiceIndex&&!correct&&<XCircle size={17} weight="fill"/>}</button>)}</div>{attempted&&<p className="mcq-explanation"><b>{correct?"Correct.":"Review:"}</b> {explanation}</p>}</article>})}</div>{done&&<div className="section-complete"><Medal size={28} weight="duotone"/><div><b>Section complete · {score}/{section.quiz.length}</b><span>{score===section.quiz.length?"Excellent—every answer is correct.":"Review the explanations or continue."}</span></div>{sectionIndex<11&&<button onClick={()=>openItem(sectionIndex+1,"lesson")}>Next section <CaretRight size={15}/></button>}</div>}</section>}
      </main>
    </div>;
  }

}
